### ISSUE TITLE
Old Lightning Strikes not going away.

### ISSUE THREAD

**Issue by TheDevFreak** [mrk-its/homeassistant-blitzortung#59]
I've got strikes still on my map from the `geo_location.lightning_strike_*` entities from over 3 days ago which still have not disappeared.

Is there an easy way to get rid of these or do I just need to wait for them to drop out of the hass DB?

**Comment by metbril** [comment]
This looks like a bug. They should be removed automatically after a set time. As far as I know.

**Comment by patman15** [comment]
Ran into the same issue on v1.3.1 with
Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

**Comment by catdogmaus** [comment]
I have the same issue still in august 2023. At the moment I have all the latest HA updates installed. In my settings, all strikes should disappear after 60min. At the moment I see on map strikes at least a day old.

**Comment by mrk-its** [comment]
it should work now

**Comment by shadowpanther** [comment]
I still have this problem as of today.

Changed the time window from 120 to 60 minutes - this did reset the counter to zero and removed the new (today's) points from the map, but I still have the ones from yesterday present.

HA 2024.7.3
